const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:chromium.executablePath()});
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8080');
 await page.evaluate(()=>{localStorage.setItem('aqsaRecords',JSON.stringify([{date:'2026-09-01',timestamp:1788307200000,grade:1,subject:'math',score:80,correct:8,total:10}]));});
 assert.match(await page.locator('#pathStatus').innerText(),/Day 1 of 365/);
 await page.locator('[data-learn="math"]').click();
 assert.ok(await page.locator('#daily-math').isVisible());
 assert.match(await page.locator('#learningDay').innerText(),/Day 1/);
 await page.locator('[data-practice="math"]').click();
 const first=await page.locator('#questionPrompt').innerText();
 for(let i=0;i<10;i++){
  const q=await page.evaluate(()=>state.questions[state.index]);
  if(q.choices)await page.getByRole('button',{name:q.a,exact:true}).click();
  else await page.locator('#typedAnswer').fill(q.a);
  await page.locator('#submitAnswer').click();
  assert.match(await page.locator('#feedback').innerText(),/Excellent!/);
  await page.locator('#nextQuestion').click();
 }
 assert.equal(await page.locator('#resultScore').innerText(),'100%');
 assert.equal(await page.evaluate(()=>getRecords().length),2,'Legacy scores preserved');
 assert.equal(await page.evaluate(()=>getRecords()[1].pathDay),1);
 await page.locator('#anotherExercise').click();
 assert.equal(await page.evaluate(()=>state.pack.variant),1);
 await page.locator('#backHome').click();
 await page.locator('[data-start="math"]').click();
 assert.equal(await page.locator('#questionPrompt').innerText(),first,'Daily set stays stable after bonus');
 await page.locator('#backHome').click();
 await page.locator('#pathDay').fill('365');await page.locator('#pathDay').dispatchEvent('change');
 await page.locator('[data-learn="science"]').click();
 assert.match(await page.locator('#daily-science').innerText(),/Year finale/);
 await page.locator('#learnGrade').selectOption('2');
 await page.locator('[data-practice="science"]').click();
 assert.equal(await page.evaluate(()=>state.questions.length),10);
 assert.ok(await page.locator('#questionPassage').isVisible());
 await page.locator('#pencilMode').click();
 assert.ok(await page.locator('#writingCanvas').isVisible());
 await page.locator('#pencilCorrect').click();
 await page.locator('#nextQuestion').click();
 await page.locator('#backHome').click();
 await page.locator('#todayPath').click();
 assert.match(await page.locator('#pathStatus').innerText(),/Day 1 of 365/);
 await page.locator('[data-page="progress"]').click();
 await page.locator('#yearStart').fill('2026-09-01');await page.locator('#yearStart').dispatchEvent('change');
 const expected=await page.evaluate(()=>YearCurriculum.dayForDate('2026-09-01',today()));
 assert.match(await page.locator('#pathStatus').innerText(),new RegExp(`Day ${expected} of 365`));
 await page.reload();
 assert.equal(await page.evaluate(()=>selectedDay()),expected);
 assert.equal(await page.evaluate(()=>getRecords().length),2);
 await page.locator('[data-page="learn"]').click();
 await page.screenshot({path:'/tmp/aqsa-year-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-page="home"]').first().click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'No horizontal overflow on phone');
 await page.locator('[data-learn="english"]').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 await page.screenshot({path:'/tmp/aqsa-year-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: navigation, scoring, explanations, stable daily/bonus sets, both grades, day 365, persistence, pencil mode and mobile layout.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
